stages:
  ee_to_race_fmt:
    cmd: ./src/etl/ee_to_json.sh data/EntranceExams data/EntranceExams_race_fmt
    deps:
    - data/EntranceExams
    - src/etl/ee_processor.py
    - src/etl/ee_to_json.sh
    - src/etl/example.py
    outs:
    - data/EntranceExams_race_fmt
  cuid_to_race_fmt:
    cmd: ./src/etl/cuid_to_json.sh data/CUID data/CUID_race_fmt
    deps:
    - data/CUID
    - src/etl/cuid_processor.py
    - src/etl/cuid_to_json.sh
    outs:
    - data/CUID_race_fmt
  qa4mre_to_race_fmt:
    cmd: ./src/etl/qa4mre_to_json.sh data/QA4MRE data/QA4MRE_race_fmt
    deps:
    - data/QA4MRE
    - src/etl/example.py
    - src/etl/qa4mre_processor.py
    - src/etl/qa4mre_to_json.sh
    outs:
    - data/QA4MRE_race_fmt
  qa4mre_split_by_lang:
    cmd: python3 src/etl/qa4mre_splitter.py -i ./data/QA4MRE_race_fmt -o data/QA4MRE_lang_splits
      -s
    deps:
    - data/QA4MRE_race_fmt
    - src/etl/qa4mre_splitter.py
    outs:
    - data/QA4MRE_lang_splits
  dl_models:
    cmd: python ./src/etl/dl_models.py -m bert-large-uncased bert-base-uncased bert-base-multilingual-cased
    deps:
    - src/etl/dl_models.py
    outs:
    - data/models/bert-base-multilingual-cased
    - data/models/bert-base-uncased
    - data/models/bert-large-uncased
